djangoScheduler/did_django_schedule_jobs/did_django_schedule_jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main"))
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoScheduler/did_django_schedule_jobs/main/urls.py
from django.urls import path
from . import views

#33389
app_name = "main"

urlpatterns = [
	
	path('', views.index, name="index"),

	]

djangoScheduler/did_django_schedule_jobs/main/models.py
from django.db import models


djangoScheduler/did_django_schedule_jobs/main/views.py
from django.shortcuts import render
from django.conf import settings

'''
Basic view for displaying our scheduled job
'''
def index(request):
	return render(request, 'main/index.html', context)



djangoScheduler/did_django_schedule_jobs/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}"></link>

  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">
    
    {% include 'main/partials/logo.html' %}

    {% block content %}

    {% endblock %}

  </div>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}

  <script src="{% static 'main.js' %}"></script>
  

</body>
</html>

djangoScheduler/did_django_schedule_jobs/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a class="active" href="javascript:void(0)">Home</a></li>
</ul>

{% endblock %}


{% block content %}

<h3 id="map">Django Schedule Jobs Demo - Home</h3>

<div class="container">


</div>


{% endblock %}

{% block extend_footer %}




{% endblock %}

djangoScheduler/did_django_schedule_jobs/main/templates/main/partials/logo.html
{% load static %}
<a href="{% url 'main:index' %}">
	<div class="brand-logo">
		<img class="logo" src="{% static 'branding/did_logo.gif' %}" />
	</div>
</a>